### PR TITLE
Melbourne/24-05-2018

### PR DESCRIPTION
**Pull request by LomaxOnTheRun**
Yatzy and FizzBuzz katas for the 24-05-2018 coding dojo session

### CODE REVIEW

**Comment by carvallegro** [comment]
@LomaxOnTheRun  I believe there is a bit of confusion here between. With the new guidelines we are dropping the folder dating system (ie `2018/24may`...) instead we just do the exercise in the kata folder and push the result.

Put the `2018/24-05-2018/fizz-buzz/index.js` file back in `katas/fizz-buzz`.

Also, how come you have modification in the yatzy folder?

**Comment by LomaxOnTheRun** [comment]
Sorry man, I'll fix all that when I get home tonight. And not sure about
the Yatzy folder, certainly didn't mean to change anything there :/

**Comment by LomaxOnTheRun** [comment]
Urgh, alright, I've tried changing the branch via terminal commands but for some reason, I don't seem to have permission to do that. To get the files up in the first place I added them manually on Github (which it seems fine to let me do), just no terminal commands. If you can get rid of the last two commits on here, I can create another pull request with my stuff. Sorry about all the hassle :/

**Comment by LomaxOnTheRun** [comment]
Alright, I've sorted out my permissions issue, and I've pushed the files to (hopefully) the right place now. Let me know if it's right, otherwise I can change it easily enough now :)

**Pull request merged**
